# AbstractCosmologicalEmulators.jl Artifacts Configuration
# Official mnuw0waCDM emulator artifacts.

[ACE_mnuw0wacdm_sigma8_basis]
git-tree-sha1 = "7012e03a7106952a1198f2382f0c327ee8a4b895"
description = "ACE emulator for mnuw0waCDM cosmology with sigma8 basis (300303 training samples)"
author = "Marco Bonici"
doi = "10.5281/zenodo.20563171"

    [[ACE_mnuw0wacdm_sigma8_basis.download]]
    url = "https://zenodo.org/api/records/20563171/files/trained_ace_mnuw0wacdm_sigma8_basis_300303.tar.xz/content"
    sha256 = "20663d7e08a40c24f69f3c9f62ac9486ff4f8051f718deca15948b7d0994eb58"

[ACE_mnuw0wacdm_ln10As_basis]
git-tree-sha1 = "9e53d889e2491046a21c91dcc67eaa63237cb2cc"
description = "ACE emulator for mnuw0waCDM cosmology with ln10As basis (300303 training samples)"
author = "Marco Bonici"
doi = "10.5281/zenodo.20563171"

    [[ACE_mnuw0wacdm_ln10As_basis.download]]
    url = "https://zenodo.org/api/records/20563171/files/trained_ace_mnuw0wacdm_ln10As_basis_300303.tar.xz/content"
    sha256 = "f7d25eaa4d5217df56f8cc0f83d269750712c6cc055833c025fef6a5f3e96cf3"
