name: Benchmark Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This is the corrected step with proper YAML syntax
      - name: Run AirspeedVelocity Benchmark # It's good practice to name steps
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        # 'working-directory' is a property of the step, at the same level as 'uses'
        working-directory: ./benchmark

        # 'with' contains the inputs for the action
        with:
          julia-version: "1"

          # IMPORTANT: The script path is now relative to the working directory
          script: "benchmarks.jl"
