# file: .github/workflows/benchmark.yml

name: Benchmark this PR
on:
  pull_request_target:
    branches: [main] # Or your default branch

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"
          # Add this line:
          path: "."
