name: Benchmark Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This is the corrected step using an environment variable
      - name: Run AirspeedVelocity Benchmark
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1

        # This 'env' block sets environment variables for this step only
        env:
          # This tells Julia to activate the environment in the ./benchmark directory
          JULIA_PROJECT: benchmark

        with:
          julia-version: "1"
          bench-on: "head"

          # We are running from the root again, so the full path to the script is needed
          script: "benchmark/benchmarks.jl"
