name: Benchmark Pull Request
on:
  pull-request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run AirspeedVelocity Benchmark
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"

          # This is the definitive fix. It tells the action to install these
          # packages into its temporary environment for every benchmark run.
          # The value must be a string representing a Julia vector.
          extra-pkgs: '["BenchmarkTools", "JSON", "SimpleChains"]'

          # This still correctly points to the script to be executed.
          script: "benchmark/benchmarks.jl"
