name: Benchmark Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run AirspeedVelocity benchmark
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"
          # run every revision with the benchmark environment
          exeflags: "--project=benchmark"
          # always use the PR’s copy of the suite
          bench-on: "head"
          script: "benchmark/benchmarks.jl"
