name: Benchmark Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run AirspeedVelocity Benchmark
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"

          # This is the key fix: It tells every Julia process spawned by the
          # action to activate the environment in the 'benchmark' directory.
          exeflags: "--project=benchmark"

          # This is still needed to point to the script file.
          # The path is relative to the repository root.
          script: "benchmark/benchmarks.jl"
