name: Benchmark Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run AirspeedVelocity Benchmark
        uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"

          # This is the single source of truth for benchmark dependencies.
          extra-pkgs: "BenchmarkTools,JSON,SimpleChains"

          # This correctly points to the script to be executed.
          script: "benchmark/benchmarks.jl"
