name: Benchmark on develop
on:
  push:
    branches:
      - develop

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code, which is now mandatory
      # because the `push` trigger doesn't do it automatically.
      - uses: actions/checkout@v4

      # Step 2: Run the benchmark action with the script explicitly defined
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1"

          # This tells the action to use the local checkout of the package
          path: "."

          # This is the key fix: explicitly point to the benchmark script
          # within the checked-out repository.
          script: "benchmark/benchmarks.jl"
