name: Benchmark this PR
on:
  pull_request: # no need for pull_request_target
    branches: [main]
# no permissions needed

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: "1.10"
          job-summary: "true"
